-- Consigli, mai ordini nelle batterie del coach (Azioni, nota 025; CLAUDE.md § 1, Ignazio 27/09: «noi non comandiamo, diamo consigli, direzione, visione»).
-- Rilettura del 04/10/2026 dei 766 testi della chat del coach (telefonata, telefonata_cliente, telefonata_partner, piano_marketing, follow_up, consulenza,
-- appuntamento_partner, non_avvenuto, preparazione_incontro): 22 frasi in cui il coach dà un ordine al partner («prova», «chiedilo», «fissate»…) diventano consigli.
-- Lasciate così: le frasi del manuale da dire al candidato («Ascolta queste tracce…», «Fidati di me, vieni solo a dare un’occhiata…»), le «E ricorda…» (ricordano
-- la voce dei leader, non danno un ordine) e le etichette «leggi…/ascolta…» dei riferimenti, che la chat corta non mostra più.
-- Ogni riga cambia solo se il testo è ancora quello letto (where … = vecchio). Copia di prima: scratchpad/copie/batterie_chat_20261004.json (sessione Azioni).
-- Da applicare con:  supabase db query --linked -f tools/coach/20261004_consigli_mai_ordini.sql

update public.coach_batterie set batteria = jsonb_set(batteria::jsonb, '{"extra","Dare Seguito","2","chiedi","1","1","1","c"}', to_jsonb('La prossima volta conviene stringere: entro 72 ore l’entusiasmo del piano è ancora vivo.'::text))::json
 where situazione = 'piano_marketing' and batteria::jsonb #>> '{"extra","Dare Seguito","2","chiedi","1","1","1","c"}' = 'La prossima volta prova a stringere: entro 72 ore l’entusiasmo del piano è ancora vivo.';
update public.coach_batterie set batteria = jsonb_set(batteria::jsonb, '{"extra","No BuonFine","1","chiedi","1","1","0","c"}', to_jsonb('La prossima volta vale la pena proporli: a volte chi non vuole l’attività prova volentieri i prodotti. E il rapporto resta vivo.'::text))::json
 where situazione = 'piano_marketing' and batteria::jsonb #>> '{"extra","No BuonFine","1","chiedi","1","1","0","c"}' = 'La prossima volta prova: a volte chi non vuole l’attività prova volentieri i prodotti. E il rapporto resta vivo.';
update public.coach_batterie set batteria = jsonb_set(batteria::jsonb, '{"extra","No BuonFine","1","chiedi","1","1","0","c"}', to_jsonb('La prossima volta vale la pena proporli: a volte chi non vuole l’attività prova volentieri i prodotti. E il rapporto resta vivo.'::text))::json
 where situazione = 'follow_up' and batteria::jsonb #>> '{"extra","No BuonFine","1","chiedi","1","1","0","c"}' = 'La prossima volta prova: a volte chi non vuole l’attività prova volentieri i prodotti. E il rapporto resta vivo.';
update public.coach_batterie set batteria = jsonb_set(batteria::jsonb, '{"extra","No BuonFine","4","chiedi","1","1","0","c"}', to_jsonb('La prossima volta può bastare una domanda: «Ti va se ci risentiamo tra qualche mese?». Così la porta resta aperta.'::text))::json
 where situazione = 'piano_marketing' and batteria::jsonb #>> '{"extra","No BuonFine","4","chiedi","1","1","0","c"}' = 'La prossima volta prova: «Ti va se ci risentiamo tra qualche mese?». Così la porta resta aperta.';
update public.coach_batterie set batteria = jsonb_set(batteria::jsonb, '{"extra","No BuonFine","4","chiedi","1","1","0","c"}', to_jsonb('La prossima volta può bastare una domanda: «Ti va se ci risentiamo tra qualche mese?». Così la porta resta aperta.'::text))::json
 where situazione = 'follow_up' and batteria::jsonb #>> '{"extra","No BuonFine","4","chiedi","1","1","0","c"}' = 'La prossima volta prova: «Ti va se ci risentiamo tra qualche mese?». Così la porta resta aperta.';
update public.coach_batterie set batteria = jsonb_set(batteria::jsonb, '{"extra","No Interesse","2","chiedi","1","1","0","c"}', to_jsonb('La prossima volta può bastare una domanda: «Ti va se ci risentiamo tra qualche mese?». Così la porta resta aperta.'::text))::json
 where situazione = 'telefonata' and batteria::jsonb #>> '{"extra","No Interesse","2","chiedi","1","1","0","c"}' = 'La prossima volta prova: «Ti va se ci risentiamo tra qualche mese?». Così la porta resta aperta.';
update public.coach_batterie set batteria = jsonb_set(batteria::jsonb, '{"nessuna","Dare Seguito","1","c"}', to_jsonb('Al prossimo incontro conviene far parlare {chi} della sua motivazione e delle sue paure: così vengono fuori.'::text))::json
 where situazione = 'piano_marketing' and batteria::jsonb #>> '{"nessuna","Dare Seguito","1","c"}' = 'Al prossimo incontro, fai parlare {chi} della sua motivazione e delle sue paure: così vengono fuori.';
update public.coach_batterie set batteria = jsonb_set(batteria::jsonb, '{"nessuna","Ulteriore Follow Up","1","c"}', to_jsonb('Al prossimo incontro conviene far parlare {chi} della sua motivazione e delle sue paure: così vengono fuori.'::text))::json
 where situazione = 'follow_up' and batteria::jsonb #>> '{"nessuna","Ulteriore Follow Up","1","c"}' = 'Al prossimo incontro, fai parlare {chi} della sua motivazione e delle sue paure: così vengono fuori.';
update public.coach_batterie set batteria = jsonb_set(batteria::jsonb, '{"altro","passi","0","c"}', to_jsonb('Cosa ti ha chiesto o detto? Se vuoi, due parole qui sotto.'::text))::json
 where situazione = 'piano_marketing' and batteria::jsonb #>> '{"altro","passi","0","c"}' = 'Cosa ti ha chiesto o detto? Scrivilo in due parole, se vuoi.';
update public.coach_batterie set batteria = jsonb_set(batteria::jsonb, '{"altro","passi","0","c"}', to_jsonb('Cosa ti ha chiesto o detto? Se vuoi, due parole qui sotto.'::text))::json
 where situazione = 'follow_up' and batteria::jsonb #>> '{"altro","passi","0","c"}' = 'Cosa ti ha chiesto o detto? Scrivilo in due parole, se vuoi.';
update public.coach_batterie set batteria = jsonb_set(batteria::jsonb, '{"altro","passi","0","c"}', to_jsonb('Cosa ti ha chiesto o detto? Se vuoi, due parole qui sotto.'::text))::json
 where situazione = 'consulenza' and batteria::jsonb #>> '{"altro","passi","0","c"}' = 'Cosa ti ha chiesto o detto? Scrivilo in due parole, se vuoi.';
update public.coach_batterie set batteria = jsonb_set(batteria::jsonb, '{"altro","passi","0","c"}', to_jsonb('Cosa ti ha chiesto o detto? Se vuoi, due parole qui sotto.'::text))::json
 where situazione = 'telefonata_cliente' and batteria::jsonb #>> '{"altro","passi","0","c"}' = 'Cosa ti ha chiesto o detto? Scrivilo in due parole, se vuoi.';
update public.coach_batterie set batteria = jsonb_set(batteria::jsonb, '{"altro","passi","0","c"}', to_jsonb('Cosa ti ha chiesto o detto? Se vuoi, due parole qui sotto.'::text))::json
 where situazione = 'telefonata' and batteria::jsonb #>> '{"altro","passi","0","c"}' = 'Cosa ti ha chiesto o detto? Scrivilo in due parole, se vuoi.';
update public.coach_batterie set batteria = jsonb_set(batteria::jsonb, '{"altro","passi","0","c"}', to_jsonb('Cosa frena {chi}? Se vuoi, due parole qui sotto.'::text))::json
 where situazione = 'telefonata_partner' and batteria::jsonb #>> '{"altro","passi","0","c"}' = 'Cosa frena {chi}? Scrivilo in due parole, se vuoi.';
update public.coach_batterie set batteria = jsonb_set(batteria::jsonb, '{"altro","passi","0","c"}', to_jsonb('Cosa frena {chi}? Se vuoi, due parole qui sotto.'::text))::json
 where situazione = 'appuntamento_partner' and batteria::jsonb #>> '{"altro","passi","0","c"}' = 'Cosa frena {chi}? Scrivilo in due parole, se vuoi.';
update public.coach_batterie set batteria = jsonb_set(batteria::jsonb, '{"extra","Ulteriore Follow Up","2","chiedi","1","1","0","c"}', to_jsonb('La prossima volta vale la pena farla: non è pressione, è aiutare a decidere.'::text))::json
 where situazione = 'follow_up' and batteria::jsonb #>> '{"extra","Ulteriore Follow Up","2","chiedi","1","1","0","c"}' = 'La prossima volta prova: non è pressione, è aiutare a decidere.';
update public.coach_batterie set batteria = jsonb_set(batteria::jsonb, '{"extra","Vendita","1","chiedi","1","1","0","c"}', to_jsonb('La prossima volta conviene ricordarla: il manuale la mette tra gli argomenti più forti, e vale su tutti i prodotti da oltre 65 anni.'::text))::json
 where situazione = 'consulenza' and batteria::jsonb #>> '{"extra","Vendita","1","chiedi","1","1","0","c"}' = 'La prossima volta ricordala: il manuale la mette tra gli argomenti più forti, e vale su tutti i prodotti da oltre 65 anni.';
update public.coach_batterie set batteria = jsonb_set(batteria::jsonb, '{"extra","No Interesse","1","chiedi","2","1","0","c"}', to_jsonb('Amway garantisce la soddisfazione su tutti i prodotti: proposta con garbo, spesso riapre la porta.'::text))::json
 where situazione = 'telefonata_cliente' and batteria::jsonb #>> '{"extra","No Interesse","1","chiedi","2","1","0","c"}' = 'Amway garantisce la soddisfazione su tutti i prodotti: proponila con garbo.';
update public.coach_batterie set batteria = jsonb_set(batteria::jsonb, '{"extra","No Interesse","1","chiedi","3","1","0","c"}', to_jsonb('La prossima volta conviene chiederlo con leggerezza: aiuta a capire, e a migliorare.'::text))::json
 where situazione = 'telefonata_cliente' and batteria::jsonb #>> '{"extra","No Interesse","1","chiedi","3","1","0","c"}' = 'La prossima volta chiedilo con leggerezza: aiuta a capire, e a migliorare.';
update public.coach_batterie set batteria = jsonb_set(batteria::jsonb, '{"extra","Ordine","1","chiedi","1","1","0","c"}', to_jsonb('La prossima volta può bastare una domanda: «Come ti trovi? C’è qualcosa che vorresti provare?»'::text))::json
 where situazione = 'telefonata_cliente' and batteria::jsonb #>> '{"extra","Ordine","1","chiedi","1","1","0","c"}' = 'La prossima volta chiedilo: «Come ti trovi? C’è qualcosa che vorresti provare?»';
update public.coach_batterie set batteria = jsonb_set(batteria::jsonb, '{"nessuna","Appuntamento","0","c"}', to_jsonb('Nessuna domanda: all’incontro conta ascoltare di cosa ha bisogno {chi}.'::text))::json
 where situazione = 'telefonata_cliente' and batteria::jsonb #>> '{"nessuna","Appuntamento","0","c"}' = 'Nessuna domanda: all’incontro, ascolta di cosa ha bisogno {chi}.';
update public.coach_batterie set batteria = jsonb_set(batteria::jsonb, '{"extra","No Show","0","c"}', to_jsonb('Il consiglio dei leader: una telefonata il giorno dopo, per sapere se è tutto a posto o se è successo qualcosa.'::text))::json
 where situazione = 'non_avvenuto' and batteria::jsonb #>> '{"extra","No Show","0","c"}' = 'Il consiglio: chiama il giorno dopo e chiedi se è tutto a posto, o se è successo qualcosa.';
update public.coach_batterie set batteria = jsonb_set(batteria::jsonb, '{"extra","Rimandato","0","c"}', to_jsonb('Il consiglio dei leader: capire se è successo qualcosa di importante, e fissare già l’incontro successivo.'::text))::json
 where situazione = 'non_avvenuto' and batteria::jsonb #>> '{"extra","Rimandato","0","c"}' = 'Il consiglio: chiedi se è successo qualcosa di importante, e fissa già l’incontro successivo.';
update public.coach_batterie set batteria = jsonb_set(batteria::jsonb, '{"extra","Rimandato","2","chiedi","2","1","0","c"}', to_jsonb('La prossima volta conviene chiederlo con leggerezza: aiuta a capire se è un imprevisto o poco interesse.'::text))::json
 where situazione = 'non_avvenuto' and batteria::jsonb #>> '{"extra","Rimandato","2","chiedi","2","1","0","c"}' = 'La prossima volta chiedilo con leggerezza: aiuta a capire se è un imprevisto o poco interesse.';
update public.coach_batterie set batteria = jsonb_set(batteria::jsonb, '{"extra","No Interesse","6","chiedi","1","1","0","c"}', to_jsonb('Allora è il momento buono: adesso, finché sei in movimento.'::text))::json
 where situazione = 'telefonata' and batteria::jsonb #>> '{"extra","No Interesse","6","chiedi","1","1","0","c"}' = 'Allora falla adesso, finché sei in movimento.';
update public.coach_batterie set batteria = jsonb_set(batteria::jsonb, '{"extra","Appuntamento","1","chiedi","0","1","0","c"}', to_jsonb('Servono carta e penna: una lista di almeno 200 nomi, con le categorie del manuale.'::text))::json
 where situazione = 'telefonata_partner' and batteria::jsonb #>> '{"extra","Appuntamento","1","chiedi","0","1","0","c"}' = 'Portate carta e penna: una lista di almeno 200 nomi, con le categorie del manuale.';
update public.coach_batterie set batteria = jsonb_set(batteria::jsonb, '{"extra","Appuntamento","1","chiedi","1","1","0","c"}', to_jsonb('Insieme si prepara la traccia per le telefonate, con due date pronte. Poi le prime chiamate, insieme.'::text))::json
 where situazione = 'telefonata_partner' and batteria::jsonb #>> '{"extra","Appuntamento","1","chiedi","1","1","0","c"}' = 'Preparate insieme la traccia per le telefonate e due date pronte. Poi le prime chiamate, insieme.';
update public.coach_batterie set batteria = jsonb_set(batteria::jsonb, '{"extra","Appuntamento","1","chiedi","4","1","0","c"}', to_jsonb('Si fissano insieme gli obiettivi del mese nei Segni Vitali, e un piano d’azione: su cosa si concentra {chi} e come lo aiuti tu.'::text))::json
 where situazione = 'telefonata_partner' and batteria::jsonb #>> '{"extra","Appuntamento","1","chiedi","4","1","0","c"}' = 'Fissate insieme gli obiettivi del mese nei Segni Vitali, e un piano d’azione: su cosa si concentra {chi} e cosa farai tu per aiutare.';
update public.coach_batterie set batteria = jsonb_set(batteria::jsonb, '{"extra","Appuntamento","2","c"}', to_jsonb('E il consiglio del manuale per il counseling: i complimenti per il lavoro fatto, e un incontro che finisce con fiducia ed entusiasmo.'::text))::json
 where situazione = 'telefonata_partner' and batteria::jsonb #>> '{"extra","Appuntamento","2","c"}' = 'E il consiglio del manuale per il counseling: fate i complimenti per il lavoro fatto, e che l’incontro finisca con fiducia ed entusiasmo.';
update public.coach_batterie set batteria = jsonb_set(batteria::jsonb, '{"nessuna","Appuntamento","0","c"}', to_jsonb('Niente freni: è il momento di accelerare. All’incontro si fissano insieme gli obiettivi del mese.'::text))::json
 where situazione = 'telefonata_partner' and batteria::jsonb #>> '{"nessuna","Appuntamento","0","c"}' = 'Niente freni: è il momento di spingere. All’incontro fissate insieme gli obiettivi del mese.';
update public.coach_batterie set batteria = jsonb_set(batteria::jsonb, '{"extra","c","Downline","2","chiedi","1","1","0","c"}', to_jsonb('La prossima volta conviene partire da lì: gli obiettivi del mese nei Segni Vitali, e un piano d’azione per raggiungerli.'::text))::json
 where situazione = 'appuntamento_partner' and batteria::jsonb #>> '{"extra","c","Downline","2","chiedi","1","1","0","c"}' = 'La prossima volta partite da lì: gli obiettivi del mese nei Segni Vitali, e un piano d’azione per raggiungerli.';

-- controllo: quante delle righe nuove sono al loro posto (devono essere 31)
select (select count(*) from public.coach_batterie where situazione = 'piano_marketing' and batteria::jsonb #>> '{"extra","Dare Seguito","2","chiedi","1","1","1","c"}' = 'La prossima volta conviene stringere: entro 72 ore l’entusiasmo del piano è ancora vivo.')
     + (select count(*) from public.coach_batterie where situazione = 'piano_marketing' and batteria::jsonb #>> '{"extra","No BuonFine","1","chiedi","1","1","0","c"}' = 'La prossima volta vale la pena proporli: a volte chi non vuole l’attività prova volentieri i prodotti. E il rapporto resta vivo.')
     + (select count(*) from public.coach_batterie where situazione = 'follow_up' and batteria::jsonb #>> '{"extra","No BuonFine","1","chiedi","1","1","0","c"}' = 'La prossima volta vale la pena proporli: a volte chi non vuole l’attività prova volentieri i prodotti. E il rapporto resta vivo.')
     + (select count(*) from public.coach_batterie where situazione = 'piano_marketing' and batteria::jsonb #>> '{"extra","No BuonFine","4","chiedi","1","1","0","c"}' = 'La prossima volta può bastare una domanda: «Ti va se ci risentiamo tra qualche mese?». Così la porta resta aperta.')
     + (select count(*) from public.coach_batterie where situazione = 'follow_up' and batteria::jsonb #>> '{"extra","No BuonFine","4","chiedi","1","1","0","c"}' = 'La prossima volta può bastare una domanda: «Ti va se ci risentiamo tra qualche mese?». Così la porta resta aperta.')
     + (select count(*) from public.coach_batterie where situazione = 'telefonata' and batteria::jsonb #>> '{"extra","No Interesse","2","chiedi","1","1","0","c"}' = 'La prossima volta può bastare una domanda: «Ti va se ci risentiamo tra qualche mese?». Così la porta resta aperta.')
     + (select count(*) from public.coach_batterie where situazione = 'piano_marketing' and batteria::jsonb #>> '{"nessuna","Dare Seguito","1","c"}' = 'Al prossimo incontro conviene far parlare {chi} della sua motivazione e delle sue paure: così vengono fuori.')
     + (select count(*) from public.coach_batterie where situazione = 'follow_up' and batteria::jsonb #>> '{"nessuna","Ulteriore Follow Up","1","c"}' = 'Al prossimo incontro conviene far parlare {chi} della sua motivazione e delle sue paure: così vengono fuori.')
     + (select count(*) from public.coach_batterie where situazione = 'piano_marketing' and batteria::jsonb #>> '{"altro","passi","0","c"}' = 'Cosa ti ha chiesto o detto? Se vuoi, due parole qui sotto.')
     + (select count(*) from public.coach_batterie where situazione = 'follow_up' and batteria::jsonb #>> '{"altro","passi","0","c"}' = 'Cosa ti ha chiesto o detto? Se vuoi, due parole qui sotto.')
     + (select count(*) from public.coach_batterie where situazione = 'consulenza' and batteria::jsonb #>> '{"altro","passi","0","c"}' = 'Cosa ti ha chiesto o detto? Se vuoi, due parole qui sotto.')
     + (select count(*) from public.coach_batterie where situazione = 'telefonata_cliente' and batteria::jsonb #>> '{"altro","passi","0","c"}' = 'Cosa ti ha chiesto o detto? Se vuoi, due parole qui sotto.')
     + (select count(*) from public.coach_batterie where situazione = 'telefonata' and batteria::jsonb #>> '{"altro","passi","0","c"}' = 'Cosa ti ha chiesto o detto? Se vuoi, due parole qui sotto.')
     + (select count(*) from public.coach_batterie where situazione = 'telefonata_partner' and batteria::jsonb #>> '{"altro","passi","0","c"}' = 'Cosa frena {chi}? Se vuoi, due parole qui sotto.')
     + (select count(*) from public.coach_batterie where situazione = 'appuntamento_partner' and batteria::jsonb #>> '{"altro","passi","0","c"}' = 'Cosa frena {chi}? Se vuoi, due parole qui sotto.')
     + (select count(*) from public.coach_batterie where situazione = 'follow_up' and batteria::jsonb #>> '{"extra","Ulteriore Follow Up","2","chiedi","1","1","0","c"}' = 'La prossima volta vale la pena farla: non è pressione, è aiutare a decidere.')
     + (select count(*) from public.coach_batterie where situazione = 'consulenza' and batteria::jsonb #>> '{"extra","Vendita","1","chiedi","1","1","0","c"}' = 'La prossima volta conviene ricordarla: il manuale la mette tra gli argomenti più forti, e vale su tutti i prodotti da oltre 65 anni.')
     + (select count(*) from public.coach_batterie where situazione = 'telefonata_cliente' and batteria::jsonb #>> '{"extra","No Interesse","1","chiedi","2","1","0","c"}' = 'Amway garantisce la soddisfazione su tutti i prodotti: proposta con garbo, spesso riapre la porta.')
     + (select count(*) from public.coach_batterie where situazione = 'telefonata_cliente' and batteria::jsonb #>> '{"extra","No Interesse","1","chiedi","3","1","0","c"}' = 'La prossima volta conviene chiederlo con leggerezza: aiuta a capire, e a migliorare.')
     + (select count(*) from public.coach_batterie where situazione = 'telefonata_cliente' and batteria::jsonb #>> '{"extra","Ordine","1","chiedi","1","1","0","c"}' = 'La prossima volta può bastare una domanda: «Come ti trovi? C’è qualcosa che vorresti provare?»')
     + (select count(*) from public.coach_batterie where situazione = 'telefonata_cliente' and batteria::jsonb #>> '{"nessuna","Appuntamento","0","c"}' = 'Nessuna domanda: all’incontro conta ascoltare di cosa ha bisogno {chi}.')
     + (select count(*) from public.coach_batterie where situazione = 'non_avvenuto' and batteria::jsonb #>> '{"extra","No Show","0","c"}' = 'Il consiglio dei leader: una telefonata il giorno dopo, per sapere se è tutto a posto o se è successo qualcosa.')
     + (select count(*) from public.coach_batterie where situazione = 'non_avvenuto' and batteria::jsonb #>> '{"extra","Rimandato","0","c"}' = 'Il consiglio dei leader: capire se è successo qualcosa di importante, e fissare già l’incontro successivo.')
     + (select count(*) from public.coach_batterie where situazione = 'non_avvenuto' and batteria::jsonb #>> '{"extra","Rimandato","2","chiedi","2","1","0","c"}' = 'La prossima volta conviene chiederlo con leggerezza: aiuta a capire se è un imprevisto o poco interesse.')
     + (select count(*) from public.coach_batterie where situazione = 'telefonata' and batteria::jsonb #>> '{"extra","No Interesse","6","chiedi","1","1","0","c"}' = 'Allora è il momento buono: adesso, finché sei in movimento.')
     + (select count(*) from public.coach_batterie where situazione = 'telefonata_partner' and batteria::jsonb #>> '{"extra","Appuntamento","1","chiedi","0","1","0","c"}' = 'Servono carta e penna: una lista di almeno 200 nomi, con le categorie del manuale.')
     + (select count(*) from public.coach_batterie where situazione = 'telefonata_partner' and batteria::jsonb #>> '{"extra","Appuntamento","1","chiedi","1","1","0","c"}' = 'Insieme si prepara la traccia per le telefonate, con due date pronte. Poi le prime chiamate, insieme.')
     + (select count(*) from public.coach_batterie where situazione = 'telefonata_partner' and batteria::jsonb #>> '{"extra","Appuntamento","1","chiedi","4","1","0","c"}' = 'Si fissano insieme gli obiettivi del mese nei Segni Vitali, e un piano d’azione: su cosa si concentra {chi} e come lo aiuti tu.')
     + (select count(*) from public.coach_batterie where situazione = 'telefonata_partner' and batteria::jsonb #>> '{"extra","Appuntamento","2","c"}' = 'E il consiglio del manuale per il counseling: i complimenti per il lavoro fatto, e un incontro che finisce con fiducia ed entusiasmo.')
     + (select count(*) from public.coach_batterie where situazione = 'telefonata_partner' and batteria::jsonb #>> '{"nessuna","Appuntamento","0","c"}' = 'Niente freni: è il momento di accelerare. All’incontro si fissano insieme gli obiettivi del mese.')
     + (select count(*) from public.coach_batterie where situazione = 'appuntamento_partner' and batteria::jsonb #>> '{"extra","c","Downline","2","chiedi","1","1","0","c"}' = 'La prossima volta conviene partire da lì: gli obiettivi del mese nei Segni Vitali, e un piano d’azione per raggiungerli.') as righe_nuove;
